// Digital Platforms Privacy Notice
// This privacy notice sets out how My Rover Limited (“we” or “us”) collect, use, and disclose information collected through your use of the My Rover website www.myrover.co and related mobile applications (the “Platforms”), other interactions with us, and from third parties, in relation to the Platforms. We may also collect, use and disclose information to the extent applicable law does not prohibit it.

// What kind of Information do we collect?
// Information we collect through the Platforms or otherwise may include personal information about you. Depending on the type of user of the Platforms you are, the personal information we collect may include your name, date of birth, addresses, email address, telephone numbers, gender, professional registration number, details about your pets (including their vaccinations, vet attendances, preferences and other details) and information on your use of the Platform and our services.

// Collection of Information:
// The information collected by us may include personal information:

// provided by you through registering an account on the Platforms, submitting an online form, request for information, survey or application through the Platforms or otherwise submitting information to us through the Platforms, or post or upload to the Platforms;
// provided to us by any veterinarian/animal clinician verified on the Platforms that have obtained your consent to disclose such information to us;
// provided to us by any third parties that have obtained your consent to disclose such information to us or that you authorise us to correct;
// relating to interactions and transactions you carry out on, or through, the Platforms;
// provided to us by you through any other method (including without limitation correspondence and discussions);
// collected through tracking your use of the Platforms, including the content you access and any services you utilise or collected through other automated technology (as further detailed below).
// You may provide information to be published or displayed (“posted”) on public areas of the Platforms, or transmitted to other users of the Platforms or third parties (collectively “User Contributions”). If you use any discussion forum feature on the Platforms, be aware that any personally identifiable information you submit there can be viewed and used by other Platforms users. Your User Contributions are posted on and transmitted to others at your own risk. We cannot control the actions of those with whom you may choose to share your User Contributions.

// Consequences for failure to provide:
// Failure to provide necessary personal information when requested may result in you not being able to fully utilise our services and/or register an account which is needed to gain access to the Platforms.

// Automatic Data Collection Technologies:
// As you navigate through and interact with the Platforms, we may use automatic data collection technologies to collect certain information about your equipment, browsing actions, and patterns. Some of this information may be linked to you personally. This information helps our Platforms function correctly, helps us understand the needs of our users and may be used for the other purposes set out in this privacy notice. Examples of this information include:

// traffic data, location data, logs and other communication data related to the Platforms;
// data related to your use of the Platforms. This includes the pages you visit, the resources and services that you access; the time you spend on each page, the date and time of your visit, referring pages (pages you came from or go to) and statistical and other aggregated data derived from your use of the Platforms;
// information about your device, computer and network connection, including your IP address, operating system, hardware version and browser type;
// if you allow our Platforms to deliver content based on your location (for example by enabling this feature on your mobile device) we may collect location data (such as through GPS, Bluetooth, or WiFi signals) including for the automated delivery of relevant content and advertising to you.
// The technologies we use for this automatic data collection may include log files, usage monitoring software and cookies. Cookies are small pieces of information that are stored on a user's device that can identify the device you are working from. The cookie file gives us details such as your IP address, platform, browser and domain (whether you are accessing the Platform from NZ or elsewhere). We may use the information generated by cookies to personalise your experience on the Platforms, make it easier for you to navigate our Platforms, and improve your experience by storing your search, posting and other viewing and usage history, and your login details (if you choose) enabling you to use certain services as a registered user without having to log on each time. We may also use cookies to provide you with certain advertisements which may be of interest to you. If you disable cookies it may limit your access to some of the Platforms' content and features. You can choose to refuse cookies by turning them off in your browser and/or deleting them from your hard drive. You do not need to have cookies turned on to use our Platforms, but your experience may be affected.

// Other Tracking Technologies:
// We advertise in a number of ways, including online through managed social media presences, and on other unaffiliated sites and mobile applications. To understand how our advertising campaigns are performing, and better understand the visitors to our Platform, we may collect certain information via our Platforms through our advertising service providers. We or our vendors use several common online tracking tools to collect information about our users, such as browser cookies, web beacons, and other similar technologies. The information we collect includes IP addresses, the number of page visits, pages viewed via our Platforms, search engine referrals, browsing activities over time and across other websites following your visit to our Platforms, and responses to advertisements and promotions on the websites and applications where we advertise.

// Third Parties, Advertising and third party links:
// We may allow third-party companies to place ads and collect information when you visit our Platforms. This may include information that will not identify you personally (such as click stream information, browser type, time and date, subject of advertisements clicked or scrolled over) and other information such as precise geo location and user device identification. This information is collected to provide advertisements about goods and services likely to be of greater interest to you. The Platforms may also contain links to a variety of advertising and third party platforms and website sources. Some of these links may request or record information from users, use cookies or other methods to collect information from you. We have no control over the content or privacy notice practices of such sites. We encourage you to review the privacy policies of such sites before engaging in any activity with them.

// Social Media and APIs:
// Our Platforms include features that are available through social media platforms (including Facebook, Twitter and Snapchat) and interactive programs. These features may collect your IP address, which pages you visit on our site, and how long for. If you're a member of a social media site, the interfaces may allow the social media site to connect your visits to this site with other personal information. Social media features and widgets are either hosted by a third party or hosted directly on our Platform. Your interactions with these features are governed by the privacy notice of the third party providing it and to the maximum extent permitted by law we accept no responsibility for the actions of those third parties.

// We may provide an application programming interface (API) to enable third party applications to interface with our Platforms. Some applications enable you to interact with us through the API in a way that requires you to log in. To do this, most of these applications will direct you through a process where you are able to let the application connect to your account.
// If you allow an application to connect to your account on our Platforms, including if you set up your account on our Platform using an API with a third party social media platform, that application will be able to access information that you can see when you are logged in tour Platforms. You should only allow applications you trust to access your account on our Platforms.
// If you set up your account on our Platforms using an API with a third party social media platform, you also consent to us obtaining and using your information from such platform.
// Mobile applications:
// If you are using our mobile application, you acknowledge and accept that we can:

// choose to send you "Push Notifications". This is a message that pops up on a mobile device at any time. "Push Notification" preferences can be configured in the application's settings (you have the option to disable the notification when you first time open the application, and you can also go to your mobile phone setting to disable the notification); and
// access your device’s location function and collect, use and disclose this information as set out in this privacy notice (you can disable the share location setting if you don't want our Platforms to access your location).
// Use of information:
// Your personal information may be used by us (and our employees, officers, agents, contractors and affiliates as defined below) for any purpose which is stated to you at the time of collection or that you otherwise authorise and for the following purposes:

// to communicate with you;
// to provide you with the goods, services, payments processing and/or information you have requested;
// verification of your identity and account for use of the Platforms, and to assist you if you forget your username or password for any of the services we provide to you via the Platforms;
// to assist in providing better services to you by tailoring them to meet your needs and to customise the Platforms to your preferences and to show you advertising and information that is most relevant to you and your interests based on the information you have provided to us or we have otherwise collected;
// to allow us to facilitate the sending of information about you and/or your pet(s) to others, when requested by you;
// to keep the Platforms and related databases (including those of identified third parties) up to date and accurate;
// to assist our contractors, suppliers and other third parties in providing services and products to us and you;
// to provide you with further information about us or other platforms or goods or services offered by us or our related companies or third parties or which we consider may be of interest to you;
// to carry out marketing, promotional and publicity purposes including direct marketing, market research and surveys;
// to keep the Platforms relevant and of interest to users, and to further develop the Platform and the services and products we offer;
// analysis in aggregate form (identifiable characteristics removed so that you will remain anonymous).
// Information Sharing and Disclosure:
// We:

// may disclose information about you, to our affiliates (which means any person or other entity which directly or indirectly controls, is controlled by or is under common control with us) for the purposes set out in section 9 above;
// may disclose information about you to our contractors, suppliers and other third parties to enable them to provide services and products to us and you, including in relation to the Platforms or as you otherwise authorise;
// may disclose information about you (if you are a veterinarian/animal clinician) to the relevant professional body in order to verify your account and status as a registered provider of such services;
// may disclose information about you and/or your pet(s) to the veterinarians/animal clincians verified on our Platforms and other third party providers or products and services that you request us to, or otherwise authorise, from time to time (such as catteries and doggie daycare);
// may disclose information about you and/or your pet(s) to our partners so that your details remain up to date in their databases (databases which you have separately given consent to hold your information), including if you are a veterinarian/animal clinician, the New Zealand Vet Association and the Vet Council New Zealand, and if you are a pet owner, the New Zealand Companion Animal Registry, New Zealand Companion Animal Council, and clinic-specific customer databases.
// may disclose information about you and/or your pet(s) to the SPCA to be used for any of the purposes outlined in their privacy policy (https://www.spca.nz/privacy);
// reserve the right to disclose your personal information when we believe it is appropriate to comply with the law, facilitate court proceedings or to protect our rights;
// may share aggregated demographic information about our user base with our affiliates, partners and advertisers.
// Data Storage:
// Any personal information that you provide to us through the Platforms will be collected and held by us (including the use of third party service providers such as Amazon Web Services Sydney, Australia).

// Data Access and Correction:
// Under the Privacy Act 1993 you have rights of access to and correction of personal information that we hold. This can be done by contacting us at the details at the end of this privacy notice.

// Competitions:
// We will collect personal information provided by you if you participate in our promotions and competitions. We collect this information in order to conduct the promotion or competition. We may disclose such information to third parties, such as agents, contractors, service providers and prize suppliers to conduct the promotion or competition. We may also use and disclose this information as otherwise set out in this privacy notice. Entry is conditional on providing this information. If the information is not fully supplied the entry may be void.

// If you provide us with the names and contact details of any other people that you would like to have participate in our contests or promotions, we will also collect this information. You promise that you have their permission to provide us with this information and for us to use it for this purpose.

// Commercial electronic messages:
// If you provide us with electronic contact details, you agree that we may send you commercial electronic messages (e.g. texts and emails) for any of the purposes set out in this privacy notice.

// Business Transitions:
// In the event of a change in ownership of all or a portion of us or the Platforms, your user information may be transferred to the new owner so that the Platforms can continue operations. In this event, your information would remain subject to this privacy notice.

// Changes in Privacy notice:
// We reserve the right to make changes to our privacy notice or alter our Platforms’ functionality. Any changes made will be updated in this privacy notice accordingly, so we encourage you to review the policy for the latest information on our privacy practices.

// Contact Details:
// If you have any questions about our privacy notice, or any other matter, please feel free to contact us. You can reach us in one of the following ways:

// Contact:	Privacy Officer
// Phone:	+64 9 360 3691
// Email:	privacy@myrover.co
// Mail:	Privacy Officer
// C/- My Rover Limited
// PO Box 106015
// Auckland City 1143
// New Zealand
// Physical Address:	Building 4, 61 Constellation Drive, Rosedale, Auckland 0632
// This privacy notice was last updated on 1st March, 2019.